### ISSUE TITLE
dont use console.log

### ISSUE THREAD

**Issue by Uzlopak** [devoplx/mediumFastifyPlugin#15]
It is really bad to use console.log, e.g. in regex.ts. 
console.log slows the node applications down

Use debuglLog from node https://nodejs.org/api/util.html#utildebuglogsection-callback
or use the fastify.logger instance

**Comment by RjManhas** [comment]
Hello thank you for raising this issue, my partner must of forget to remove the console logs since they are only there for debugging.

**Comment by TheHellTower** [comment]
> It is really bad to use console.log, e.g. in regex.ts. console.log slows the node applications down
> 
> Use debuglLog from node https://nodejs.org/api/util.html#utildebuglogsection-callback or use the fastify.logger instance

Hello, the `console.log` if any left in the actual plugin code are a mistake.. But I take this in notes ! I will see `fastify.logger` and `debuglLog`.. But in the example it was on purpose to verify the data output even thought I might remove `console.log` everywhere and replace with one of the specified ones. Thanks !

**Comment by Uzlopak** [comment]
Happens to the best of us too. ;)

**Comment by RjManhas** [comment]
merged
