### ISSUE TITLE
case study: what not to do with readingTimeRegex 

### ISSUE THREAD

**Issue by Uzlopak** [devoplx/mediumFastifyPlugin#17]
First of all, readingTimeRegex is actually about parsing a string to a number. The suffix `Regex` indicates, that it is a Regex (why do you use again typescript, if you name it that way) but it is a function.

So rename it to `parseReadingTime`

The numberRegex is always created in the function. This is a performance bottleneck. Just declare the regex outside the function. Rename it to `readingTimeRegex`, because numberRegex is to generic. I personally dont use Regex as a suffix but RE, but this is personal flavor.

You are using `.match()` just to check if the regex matches. It creates an match Object, which you are basically just use to check if you have a match. You are not even using a capturing group but access the original string in by accessing the 0 value of the match Object. Use `.test()` instead, which just returns a boolean. 

remove the `console.log`-calls. 

You are assigning number only if you match and return it immediatly. Later you return an Error if number is undefined and if not you return number, which will be probably never hit so you have there dead code.  So you can remove the last `return number`.

```js
const readingTimeRE = /^(\d+)\s+min\s+read$/;

function parseTime(readingTime: string): number | Error => {
    if (readingTimeRE.test(readingTime)) {
        return parseInt(readingTime, 10);
    }

    return new Error('expected number');
};
```

or if you want it even shorter:

```js
const readingTimeRE = /^(\d+)\s+min\s+read$/;

function parseTime(readingTime: string): number | Error => {
  return readingTimeRE.test(readingTime)
    ? parseInt(readingTime, 10)
    : new Error('expected number')
};
```

**Comment by RjManhas** [comment]
merged
